# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release Package

on:
  # æ‰‹åŠ¨è§¦å‘
  workflow_dispatch:

  # æ¨é€ tag æ˜¯ v*.*.*æ—¶è§¦å‘
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    # æ‰“åŒ…
    name: Build distribution ğŸ“¦
    runs-on: ubuntu-latest

    steps:
      # clone ä»“åº“
      - uses: actions/checkout@v4

      # è®¾ç½® Pythonç¯å¢ƒå’Œç‰ˆæœ¬
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # å®‰è£… build
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user          

      # æ‰“åŒ…ä½ çš„é¡¹ç›®
      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      # å°†æ‰“åŒ…å¾—åˆ°çš„æ–‡ä»¶ä¸Šä¼ åˆ° artifact
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
          retention-days: 1 # 1 å¤©ååˆ é™¤ artifact

  publish-to-pypi:
    # ä¸Šä¼ åˆ° PPyPIypi
    name: >-
      Publish Python ğŸ distribution ğŸ“¦ to PyPI      
    if: startsWith(github.ref, 'refs/tags/') 
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/rainpy
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      # ä» artifact ä¸‹è½½æ‰“åŒ…çš„æ–‡ä»¶
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      #  é€šè¿‡ pypa/gh-action-pypi-publish è¿™ä¸ª action å‘å¸ƒåˆ° PyPI
      - name: Publish distribution ğŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1